/*
 * Copyright (C) Schweizerische Bundesbahnen SBB, 2016.
 */

package ch.sbb.myproject.controller;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import ch.sbb.myproject.model.Greeting;

/**
 * Simple REST controller with Spring MVC. For a more complete REST sample refer
 * to <a href="https://code.sbb.ch/projects/KD_ESTA/repos/esta-cloud-demo-customer/browse/src/main/java/ch/sbb/esta/cloud/controller/CustomerController.java">CustomerController.java</a>
 *
 * @author ue64007 (Manuel Wallrapp), generated by ESTA Initializr
 * @since 1.0.0, 2017.
 */
@RestController
@CrossOrigin
public class SampleController {

    /**
     * Get a personal greeting - or if no name is specified a greeting to the world.
     *
     * @param name Name used in greeting (not required, default value: "Welt").
     * @return Greeting
     */
    @RequestMapping(value="/greeting", method= RequestMethod.GET)
    public ResponseEntity<?> getGreeting(@RequestParam(value = "name", required = false, defaultValue = "Welt") String name) {
        return new ResponseEntity<>(new Greeting("de", "Hallo " + name), HttpStatus.OK);
    }
}
