/*
 * Copyright (C) Schweizerische Bundesbahnen SBB, 2016.
 */

package ch.sbb.myproject.model;

/**
 * Simple Greeting model class.
 *
 * @author ue64007 (Manuel Wallrapp), generated by ESTA Initializr
 * @since 0.0.9, 2016.
 */
public final class Greeting {
    private String language;
    private String text;

    public Greeting(String language, String text) {
        this.language = language;
        this.text = text;
    }

    public String getLanguage() {
        return language;
    }
    public String getText() {
        return text;
    }
}
