/*
 * Copyright (C) Schweizerische Bundesbahnen SBB, 2016.
 */

package ch.sbb.tms.rest;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * Simple REST controller with Spring MVC. For a more complete REST sample refer
 * to <a href="https://code.sbb.ch/projects/KD_ESTA/repos/esta-cloud-demo-customer/browse/src/main/java/ch/sbb/esta/cloud/controller/CustomerController.java">CustomerController.java</a>
 *
 * @author ue64007 (Manuel Wallrapp), generated by ESTA Initializr
 * @since 1.0.0, 2017.
 */
@RestController
@CrossOrigin
public class GleisBelegungController {

    /**
     * 
     * @param name
     * @return
     */
    @RequestMapping(value="/greeting", method= RequestMethod.GET)
    public ResponseEntity<?> getGreeting(@RequestParam(value = "name", required = false, defaultValue = "Welt") String name) {
        return new ResponseEntity<>(new Greeting("de", "Hallo " + name), HttpStatus.OK);
    }
}
